version: "3.3"

services:
  app:
    build: .
    container_name: "catalog"
    restart: always
    ports:
      - "8082:8082"
    networks:
      - bacoder_net
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    container_name: "catalogDb"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
    - bacoder_net
    volumes:
      - ./mysql_data:/var/lib/mysql:rw,z

volumes:
  mysql_data:
networks:
     bacoder_net:
      external: true